spring:
  application:
    name: spring-boot-react-deploy
    upload:
      path: ${user.home}/.test1
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 1MB
server:
  port: 10000

